import React from 'react'

function PositionTable () {
  return (
    <table>
      <tr>
        <th>Currency Pair</th>
        <th>Usual Positon Per US50,000 Balance</th>
        <th>Usual Positon Per US25,000 Balance</th>
        <th>Usual Positon Per US12,500 Balance</th>
      </tr>
      <tr>
        <td>AUD/USD</td>
        <td>1.57</td>
        <td>1.22</td>
        <td>0.61</td>
      </tr>
      <tr>
        <td>AUD/NZD</td>
        <td>1.57</td>
        <td>1.22</td>
        <td>0.61</td>
      </tr>
      <tr>
        <td>AUD/CAD</td>
        <td>1.57</td>
        <td>1.22</td>
        <td>0.61</td>
      </tr>
      <tr>
        <td>AUD/CHF</td>
        <td>1.57</td>
        <td>1.28</td>
        <td>0.64</td>
      </tr>
      <tr>
        <td>AUD/JPY</td>
        <td>1.57</td>
        <td>1.28</td>
        <td>0.64</td>
      </tr>
      <tr>
        <td>NZD/USD</td>
        <td>1.66</td>
        <td>1.28</td>
        <td>0.64</td>
      </tr>
      <tr>
        <td>NZD/JPY</td>
        <td>1.66</td>
        <td>1.28</td>
        <td>0.64</td>
      </tr>

      <tr>
        <td>NZD/CHF</td>
        <td>1.66</td>
        <td>1.28</td>
        <td>0.62</td>
      </tr>
      <tr>
        <td>NZD/CAD</td>
        <td>1.66</td>
        <td>1.28</td>
        <td>0.62</td>
      </tr>
      <tr>
        <td>GBP/USD</td>
        <td>0.81</td>
        <td>0.72</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>GBP/JPY</td>
        <td>0.81</td>
        <td>0.72</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>GBP/CAD</td>
        <td>0.81</td>
        <td>0.72</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>GBP/AUD</td>
        <td>0.81</td>
        <td>0.74</td>
        <td>0.38</td>
      </tr>
      <tr>
        <td>GBP/NZD</td>
        <td>0.81</td>
        <td>0.74</td>
        <td>0.37</td>
      </tr>
      <tr>
        <td>GBP/CHF</td>
        <td>0.81</td>
        <td>0.76</td>
        <td>0.37</td>
      </tr>
      <tr>
        <td>EUR/AUD</td>
        <td>0.93</td>
        <td>0.76</td>
        <td>0.38</td>
      </tr>
      <tr>
        <td>EUR/NZD</td>
        <td>0.93</td>
        <td>0.72</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>EUR/USD</td>
        <td>0.93</td>
        <td>0.72</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>EUR/JPY</td>
        <td>0.72</td>
        <td>0.70</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>EUR/GBP</td>
        <td>0.93</td>
        <td>0.86</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>EUR/CAD</td>
        <td>0.93</td>
        <td>0.74</td>
        <td>0.38</td>
      </tr>
      <tr>
        <td>EUR/CHF</td>
        <td>0.93</td>
        <td>0.72</td>
        <td>0.36</td>
      </tr>
      <tr>
        <td>USD/JPY</td>
        <td>1.00</td>
        <td>0.80</td>
        <td>0.40</td>
      </tr>
      <tr>
        <td>USD/CAD</td>
        <td>1.00</td>
        <td>0.80</td>
        <td>0.40</td>
      </tr>
      <tr>
        <td>CHF/JPY</td>
        <td>0.98</td>
        <td>0.98</td>
        <td>0.48</td>
      </tr>
      <tr>
        <td>CAD/CHF</td>
        <td>1.41</td>
        <td>1.40</td>
        <td>0.68</td>
      </tr>
      <tr>
        <td>CAD/JPY</td>
        <td>1.41</td>
        <td>1.40</td>
        <td>0.68</td>
      </tr>
      <tr>
        <td>XAU/USD</td>
        <td>0.24</td>
        <td>0.24</td>
        <td>0.12</td>
      </tr>
      <tr>
        <td>XAG/USD</td>
        <td>0.24</td>
        <td>0.24</td>
        <td>0.12</td>
      </tr>
      <tr>
        <td>USDCHF</td>
        <td>1.00</td>
        <td>1.00</td>
        <td>0.48</td>
      </tr>
    </table>
  )
}

export default PositionTable
